/*
================================================================================
CAREVIEW - GOLD LAYER (Analytics)
================================================================================
Purpose: Aggregated metrics, KPIs, and business insights
Tables: Patient summaries, department metrics, revenue analysis
Run As: CAREVIEW_ADMIN or CAREVIEW_ANALYST
================================================================================
*/

-- ============================================================================
-- 1. PATIENT SUMMARY - Comprehensive patient overview
-- ============================================================================
CREATE OR REPLACE TABLE CAREVIEW_DB.GOLD.PATIENT_SUMMARY AS
SELECT 
    P.PATIENT_ID,
    P.FIRST_NAME,
    P.LAST_NAME,
    P.AGE,
    P.GENDER,
    P.BLOOD_TYPE,
    COUNT(DISTINCT V.VISIT_ID) AS TOTAL_VISITS,
    MAX(V.VISIT_DATE) AS LAST_VISIT_DATE,
    COUNT(DISTINCT D.DIAGNOSIS_ID) AS TOTAL_DIAGNOSES,
    MAX(D.SEVERITY_LEVEL) AS MAX_SEVERITY_LEVEL,
    COUNT(DISTINCT T.TREATMENT_ID) AS TOTAL_TREATMENTS,
    SUM(B.AMOUNT) AS TOTAL_BILLED,
    SUM(CASE WHEN B.PAYMENT_STATUS = 'PAID' THEN B.AMOUNT ELSE 0 END) AS TOTAL_PAID,
    SUM(CASE WHEN B.PAYMENT_STATUS IN ('PENDING', 'DENIED') THEN B.AMOUNT ELSE 0 END) AS OUTSTANDING_BALANCE
FROM CAREVIEW_DB.SILVER.PATIENTS P
LEFT JOIN CAREVIEW_DB.SILVER.VISITS V ON P.PATIENT_ID = V.PATIENT_ID
LEFT JOIN CAREVIEW_DB.SILVER.DIAGNOSES D ON V.VISIT_ID = D.VISIT_ID
LEFT JOIN CAREVIEW_DB.SILVER.TREATMENTS T ON V.VISIT_ID = T.VISIT_ID
LEFT JOIN CAREVIEW_DB.SILVER.BILLING B ON V.VISIT_ID = B.VISIT_ID
GROUP BY P.PATIENT_ID, P.FIRST_NAME, P.LAST_NAME, P.AGE, P.GENDER, P.BLOOD_TYPE;

-- ============================================================================
-- 2. DEPARTMENT METRICS - Department performance KPIs
-- ============================================================================
CREATE OR REPLACE TABLE CAREVIEW_DB.GOLD.DEPARTMENT_METRICS AS
SELECT 
    V.DEPARTMENT,
    COUNT(DISTINCT V.VISIT_ID) AS TOTAL_VISITS,
    COUNT(DISTINCT V.PATIENT_ID) AS UNIQUE_PATIENTS,
    ROUND(AVG(V.LENGTH_OF_STAY_DAYS), 2) AS AVG_LENGTH_OF_STAY,
    COUNT(CASE WHEN V.VISIT_TYPE = 'EMERGENCY' THEN 1 END) AS EMERGENCY_VISITS,
    COUNT(CASE WHEN V.VISIT_TYPE = 'INPATIENT' THEN 1 END) AS INPATIENT_VISITS,
    COUNT(CASE WHEN V.VISIT_TYPE = 'OUTPATIENT' THEN 1 END) AS OUTPATIENT_VISITS,
    SUM(B.AMOUNT) AS TOTAL_REVENUE,
    ROUND(AVG(B.AMOUNT), 2) AS AVG_BILL_AMOUNT,
    COUNT(DISTINCT D.DIAGNOSIS_ID) AS TOTAL_DIAGNOSES
FROM CAREVIEW_DB.SILVER.VISITS V
LEFT JOIN CAREVIEW_DB.SILVER.BILLING B ON V.VISIT_ID = B.VISIT_ID
LEFT JOIN CAREVIEW_DB.SILVER.DIAGNOSES D ON V.VISIT_ID = D.VISIT_ID
GROUP BY V.DEPARTMENT
ORDER BY TOTAL_REVENUE DESC;

-- ============================================================================
-- 3. MONTHLY REVENUE - Time-based financial analysis
-- ============================================================================
CREATE OR REPLACE TABLE CAREVIEW_DB.GOLD.MONTHLY_REVENUE AS
SELECT 
    DATE_TRUNC('MONTH', B.BILL_DATE) AS REVENUE_MONTH,
    B.DEPARTMENT,
    COUNT(DISTINCT B.BILL_ID) AS BILL_COUNT,
    SUM(B.AMOUNT) AS TOTAL_AMOUNT,
    SUM(CASE WHEN B.PAYMENT_STATUS = 'PAID' THEN B.AMOUNT ELSE 0 END) AS PAID_AMOUNT,
    SUM(CASE WHEN B.PAYMENT_STATUS = 'INSURANCE' THEN B.AMOUNT ELSE 0 END) AS INSURANCE_AMOUNT,
    SUM(CASE WHEN B.PAYMENT_STATUS = 'PENDING' THEN B.AMOUNT ELSE 0 END) AS PENDING_AMOUNT,
    SUM(CASE WHEN B.PAYMENT_STATUS = 'DENIED' THEN B.AMOUNT ELSE 0 END) AS DENIED_AMOUNT,
    ROUND(SUM(CASE WHEN B.PAYMENT_STATUS = 'PAID' THEN B.AMOUNT ELSE 0 END) / 
          NULLIF(SUM(B.AMOUNT), 0) * 100, 2) AS COLLECTION_RATE_PCT
FROM CAREVIEW_DB.SILVER.BILLING B
GROUP BY DATE_TRUNC('MONTH', B.BILL_DATE), B.DEPARTMENT
ORDER BY REVENUE_MONTH DESC, TOTAL_AMOUNT DESC;

-- ============================================================================
-- 4. DIAGNOSIS ANALYTICS - Disease pattern analysis
-- ============================================================================
CREATE OR REPLACE TABLE CAREVIEW_DB.GOLD.DIAGNOSIS_ANALYTICS AS
SELECT 
    D.DIAGNOSIS_CODE,
    D.DIAGNOSIS_NAME,
    COUNT(DISTINCT D.DIAGNOSIS_ID) AS DIAGNOSIS_COUNT,
    COUNT(DISTINCT D.PATIENT_ID) AS AFFECTED_PATIENTS,
    ROUND(AVG(D.SEVERITY_LEVEL), 2) AS AVG_SEVERITY,
    COUNT(CASE WHEN D.SEVERITY_TEXT = 'CRITICAL' THEN 1 END) AS CRITICAL_CASES,
    COUNT(CASE WHEN D.SEVERITY_TEXT = 'SEVERE' THEN 1 END) AS SEVERE_CASES,
    COUNT(CASE WHEN D.SEVERITY_TEXT = 'MODERATE' THEN 1 END) AS MODERATE_CASES,
    COUNT(CASE WHEN D.SEVERITY_TEXT = 'MILD' THEN 1 END) AS MILD_CASES,
    MIN(D.DIAGNOSIS_DATE) AS FIRST_OCCURRENCE,
    MAX(D.DIAGNOSIS_DATE) AS LAST_OCCURRENCE
FROM CAREVIEW_DB.SILVER.DIAGNOSES D
GROUP BY D.DIAGNOSIS_CODE, D.DIAGNOSIS_NAME
ORDER BY DIAGNOSIS_COUNT DESC;
