-- ============================================
-- CAREVIEW PROJECT - AUDIT & VERIFICATION
-- Purpose: Validate data quality across Bronze, Silver, and Gold layers
-- ============================================


-- ============================================
-- SECTION 1: ROW COUNTS BY LAYER
-- Purpose: Count total records in each table to track data volume
-- ============================================

-- Bronze Layer (Raw Data) - Count records in each source table
SELECT 'BRONZE' AS LAYER, 'PATIENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.BRONZE.PATIENTS;
SELECT 'BRONZE' AS LAYER, 'VISITS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.BRONZE.VISITS;
SELECT 'BRONZE' AS LAYER, 'DIAGNOSES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.BRONZE.DIAGNOSES;
SELECT 'BRONZE' AS LAYER, 'TREATMENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.BRONZE.TREATMENTS;
SELECT 'BRONZE' AS LAYER, 'BILLING' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.BRONZE.BILLING;

-- Silver Layer (Cleaned Data) - Count records after data cleansing
SELECT 'SILVER' AS LAYER, 'PATIENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.SILVER.PATIENTS;
SELECT 'SILVER' AS LAYER, 'VISITS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.SILVER.VISITS;
SELECT 'SILVER' AS LAYER, 'DIAGNOSES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.SILVER.DIAGNOSES;
SELECT 'SILVER' AS LAYER, 'TREATMENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.SILVER.TREATMENTS;
SELECT 'SILVER' AS LAYER, 'BILLING' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.SILVER.BILLING;

-- Gold Layer (Aggregated Data) - Count records in analytics tables
SELECT 'GOLD' AS LAYER, 'PATIENT_SUMMARY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.GOLD.PATIENT_SUMMARY;
SELECT 'GOLD' AS LAYER, 'DEPARTMENT_METRICS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.GOLD.DEPARTMENT_METRICS;
SELECT 'GOLD' AS LAYER, 'MONTHLY_REVENUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.GOLD.MONTHLY_REVENUE;
SELECT 'GOLD' AS LAYER, 'DIAGNOSIS_ANALYTICS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CAREVIEW_DB.GOLD.DIAGNOSIS_ANALYTICS;


-- ============================================
-- SECTION 2: NULL CHECKS ON PRIMARY KEYS
-- Purpose: Ensure no primary key columns have NULL values (data integrity)
-- Expected Result: All NULL_COUNT values should be 0
-- ============================================

SELECT 'BRONZE.PATIENTS' AS TABLE_NAME, 'PATIENT_ID' AS COLUMN_NAME, COUNT(*) AS NULL_COUNT FROM CAREVIEW_DB.BRONZE.PATIENTS WHERE PATIENT_ID IS NULL;
SELECT 'BRONZE.VISITS' AS TABLE_NAME, 'VISIT_ID' AS COLUMN_NAME, COUNT(*) AS NULL_COUNT FROM CAREVIEW_DB.BRONZE.VISITS WHERE VISIT_ID IS NULL;
SELECT 'BRONZE.DIAGNOSES' AS TABLE_NAME, 'DIAGNOSIS_ID' AS COLUMN_NAME, COUNT(*) AS NULL_COUNT FROM CAREVIEW_DB.BRONZE.DIAGNOSES WHERE DIAGNOSIS_ID IS NULL;
SELECT 'BRONZE.TREATMENTS' AS TABLE_NAME, 'TREATMENT_ID' AS COLUMN_NAME, COUNT(*) AS NULL_COUNT FROM CAREVIEW_DB.BRONZE.TREATMENTS WHERE TREATMENT_ID IS NULL;
SELECT 'BRONZE.BILLING' AS TABLE_NAME, 'BILL_ID' AS COLUMN_NAME, COUNT(*) AS NULL_COUNT FROM CAREVIEW_DB.BRONZE.BILLING WHERE BILL_ID IS NULL;


-- ============================================
-- SECTION 3: DUPLICATE CHECKS
-- Purpose: Find duplicate primary keys (should return no rows if data is clean)
-- Expected Result: No rows returned means no duplicates exist
-- ============================================

SELECT 'BRONZE.PATIENTS' AS TABLE_NAME, PATIENT_ID, COUNT(*) AS DUPLICATE_COUNT FROM CAREVIEW_DB.BRONZE.PATIENTS GROUP BY PATIENT_ID HAVING COUNT(*) > 1;
SELECT 'BRONZE.VISITS' AS TABLE_NAME, VISIT_ID, COUNT(*) AS DUPLICATE_COUNT FROM CAREVIEW_DB.BRONZE.VISITS GROUP BY VISIT_ID HAVING COUNT(*) > 1;
SELECT 'BRONZE.DIAGNOSES' AS TABLE_NAME, DIAGNOSIS_ID, COUNT(*) AS DUPLICATE_COUNT FROM CAREVIEW_DB.BRONZE.DIAGNOSES GROUP BY DIAGNOSIS_ID HAVING COUNT(*) > 1;
SELECT 'BRONZE.TREATMENTS' AS TABLE_NAME, TREATMENT_ID, COUNT(*) AS DUPLICATE_COUNT FROM CAREVIEW_DB.BRONZE.TREATMENTS GROUP BY TREATMENT_ID HAVING COUNT(*) > 1;
SELECT 'BRONZE.BILLING' AS TABLE_NAME, BILL_ID, COUNT(*) AS DUPLICATE_COUNT FROM CAREVIEW_DB.BRONZE.BILLING GROUP BY BILL_ID HAVING COUNT(*) > 1;


-- ============================================
-- SECTION 4: REFERENTIAL INTEGRITY (ORPHAN RECORDS)
-- Purpose: Find records that reference non-existent parent records
-- Example: A visit referencing a patient that doesn't exist
-- Expected Result: No rows returned means all foreign keys are valid
-- ============================================

-- Find visits linked to patients that don't exist
SELECT 'VISITS WITH INVALID PATIENT' AS CHECK_NAME, v.* 
FROM CAREVIEW_DB.BRONZE.VISITS v 
LEFT JOIN CAREVIEW_DB.BRONZE.PATIENTS p ON v.PATIENT_ID = p.PATIENT_ID 
WHERE p.PATIENT_ID IS NULL;

-- Find diagnoses linked to visits that don't exist
SELECT 'DIAGNOSES WITH INVALID VISIT' AS CHECK_NAME, d.* 
FROM CAREVIEW_DB.BRONZE.DIAGNOSES d 
LEFT JOIN CAREVIEW_DB.BRONZE.VISITS v ON d.VISIT_ID = v.VISIT_ID 
WHERE v.VISIT_ID IS NULL;

-- Find treatments linked to visits that don't exist
SELECT 'TREATMENTS WITH INVALID VISIT' AS CHECK_NAME, t.* 
FROM CAREVIEW_DB.BRONZE.TREATMENTS t 
LEFT JOIN CAREVIEW_DB.BRONZE.VISITS v ON t.VISIT_ID = v.VISIT_ID 
WHERE v.VISIT_ID IS NULL;

-- Find billing records linked to visits that don't exist
SELECT 'BILLING WITH INVALID VISIT' AS CHECK_NAME, b.* 
FROM CAREVIEW_DB.BRONZE.BILLING b 
LEFT JOIN CAREVIEW_DB.BRONZE.VISITS v ON b.VISIT_ID = v.VISIT_ID 
WHERE v.VISIT_ID IS NULL;


-- ============================================
-- SECTION 5: DATA QUALITY CHECKS
-- Purpose: Find records with logically invalid data
-- Expected Result: No rows returned means data is valid
-- ============================================

-- Patients with birth date in the future (impossible)
SELECT 'FUTURE DATE_OF_BIRTH' AS ISSUE, p.* 
FROM CAREVIEW_DB.BRONZE.PATIENTS p 
WHERE DATE_OF_BIRTH > CURRENT_DATE();

-- Billing records with negative amounts (suspicious)
SELECT 'NEGATIVE BILLING AMOUNT' AS ISSUE, b.* 
FROM CAREVIEW_DB.BRONZE.BILLING b 
WHERE AMOUNT < 0;

-- Visits where discharge happened before the visit (impossible)
SELECT 'DISCHARGE BEFORE VISIT' AS ISSUE, v.* 
FROM CAREVIEW_DB.BRONZE.VISITS v 
WHERE DISCHARGE_DATE < VISIT_DATE;

-- Patients with invalid gender values
SELECT 'INVALID GENDER VALUE' AS ISSUE, p.* 
FROM CAREVIEW_DB.BRONZE.PATIENTS p 
WHERE UPPER(GENDER) NOT IN ('MALE', 'FEMALE', 'M', 'F');

-- Patients with invalid blood type values
SELECT 'INVALID BLOOD TYPE' AS ISSUE, p.* 
FROM CAREVIEW_DB.BRONZE.PATIENTS p 
WHERE UPPER(BLOOD_TYPE) NOT IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-');


-- ============================================
-- SECTION 6: BRONZE TO SILVER LAYER VERIFICATION
-- Purpose: Verify data was correctly transformed from Bronze to Silver
-- ============================================

-- Compare record counts between Bronze and Silver layers
-- Shows how many records were dropped during cleaning
SELECT 'PATIENTS' AS TABLE_NAME, 
       b.cnt AS BRONZE_COUNT, 
       s.cnt AS SILVER_COUNT, 
       b.cnt - s.cnt AS RECORDS_DROPPED
FROM (SELECT COUNT(*) cnt FROM CAREVIEW_DB.BRONZE.PATIENTS) b,
     (SELECT COUNT(*) cnt FROM CAREVIEW_DB.SILVER.PATIENTS) s;

SELECT 'VISITS' AS TABLE_NAME, 
       b.cnt AS BRONZE_COUNT, 
       s.cnt AS SILVER_COUNT, 
       b.cnt - s.cnt AS RECORDS_DROPPED
FROM (SELECT COUNT(*) cnt FROM CAREVIEW_DB.BRONZE.VISITS) b,
     (SELECT COUNT(*) cnt FROM CAREVIEW_DB.SILVER.VISITS) s;

SELECT 'DIAGNOSES' AS TABLE_NAME, 
       b.cnt AS BRONZE_COUNT, 
       s.cnt AS SILVER_COUNT, 
       b.cnt - s.cnt AS RECORDS_DROPPED
FROM (SELECT COUNT(*) cnt FROM CAREVIEW_DB.BRONZE.DIAGNOSES) b,
     (SELECT COUNT(*) cnt FROM CAREVIEW_DB.SILVER.DIAGNOSES) s;

SELECT 'TREATMENTS' AS TABLE_NAME, 
       b.cnt AS BRONZE_COUNT, 
       s.cnt AS SILVER_COUNT, 
       b.cnt - s.cnt AS RECORDS_DROPPED
FROM (SELECT COUNT(*) cnt FROM CAREVIEW_DB.BRONZE.TREATMENTS) b,
     (SELECT COUNT(*) cnt FROM CAREVIEW_DB.SILVER.TREATMENTS) s;

SELECT 'BILLING' AS TABLE_NAME, 
       b.cnt AS BRONZE_COUNT, 
       s.cnt AS SILVER_COUNT, 
       b.cnt - s.cnt AS RECORDS_DROPPED
FROM (SELECT COUNT(*) cnt FROM CAREVIEW_DB.BRONZE.BILLING) b,
     (SELECT COUNT(*) cnt FROM CAREVIEW_DB.SILVER.BILLING) s;

-- Verify AGE column was calculated correctly from DATE_OF_BIRTH
-- Returns rows where AGE doesn't match the expected calculation
SELECT 'AGE CALCULATION CHECK' AS CHECK_NAME, 
       PATIENT_ID, 
       DATE_OF_BIRTH, 
       AGE, 
       DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE()) AS EXPECTED_AGE
FROM CAREVIEW_DB.SILVER.PATIENTS 
WHERE AGE != DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE());

-- Verify LENGTH_OF_STAY was calculated correctly
-- Returns rows where length of stay doesn't match expected calculation
SELECT 'LENGTH_OF_STAY CHECK' AS CHECK_NAME,
       VISIT_ID,
       VISIT_DATE,
       DISCHARGE_DATE,
       LENGTH_OF_STAY_DAYS,
       DATEDIFF('DAY', VISIT_DATE, DISCHARGE_DATE) AS EXPECTED_LOS
FROM CAREVIEW_DB.SILVER.VISITS
WHERE LENGTH_OF_STAY_DAYS != DATEDIFF('DAY', VISIT_DATE, DISCHARGE_DATE);

-- Verify SEVERITY_LEVEL mapping is correct
-- MILD=1, MODERATE=2, SEVERE=3, CRITICAL=4
SELECT 'SEVERITY MAPPING CHECK' AS CHECK_NAME, 
       DIAGNOSIS_ID, 
       SEVERITY_TEXT, 
       SEVERITY_LEVEL
FROM CAREVIEW_DB.SILVER.DIAGNOSES 
WHERE (SEVERITY_TEXT = 'MILD' AND SEVERITY_LEVEL != 1)
   OR (SEVERITY_TEXT = 'MODERATE' AND SEVERITY_LEVEL != 2)
   OR (SEVERITY_TEXT = 'SEVERE' AND SEVERITY_LEVEL != 3)
   OR (SEVERITY_TEXT = 'CRITICAL' AND SEVERITY_LEVEL != 4);


-- ============================================
-- SECTION 7: SILVER TO GOLD LAYER VERIFICATION
-- Purpose: Verify aggregations in Gold layer match Silver layer totals
-- ============================================

-- Check: Total visits in PATIENT_SUMMARY should equal Silver visit count
SELECT 'PATIENT_SUMMARY VISITS' AS METRIC,
       g.total AS GOLD_TOTAL_VISITS,
       s.total AS SILVER_TOTAL_VISITS,
       CASE WHEN g.total = s.total THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (SELECT SUM(TOTAL_VISITS) total FROM CAREVIEW_DB.GOLD.PATIENT_SUMMARY) g,
     (SELECT COUNT(*) total FROM CAREVIEW_DB.SILVER.VISITS) s;

-- Check: Total visits in DEPARTMENT_METRICS should equal Silver visit count
SELECT 'DEPARTMENT_METRICS VISITS' AS METRIC,
       g.total AS GOLD_TOTAL_VISITS,
       s.total AS SILVER_TOTAL_VISITS,
       CASE WHEN g.total = s.total THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (SELECT SUM(TOTAL_VISITS) total FROM CAREVIEW_DB.GOLD.DEPARTMENT_METRICS) g,
     (SELECT COUNT(*) total FROM CAREVIEW_DB.SILVER.VISITS) s;

-- Check: Total revenue in MONTHLY_REVENUE should equal Silver billing total
SELECT 'MONTHLY_REVENUE TOTAL' AS METRIC,
       g.total AS GOLD_TOTAL_REVENUE,
       s.total AS SILVER_TOTAL_REVENUE,
       CASE WHEN g.total = s.total THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (SELECT SUM(TOTAL_AMOUNT) total FROM CAREVIEW_DB.GOLD.MONTHLY_REVENUE) g,
     (SELECT SUM(AMOUNT) total FROM CAREVIEW_DB.SILVER.BILLING) s;

-- Check: Total diagnoses in DIAGNOSIS_ANALYTICS should equal Silver count
SELECT 'DIAGNOSIS_ANALYTICS COUNT' AS METRIC,
       g.total AS GOLD_TOTAL_DIAGNOSES,
       s.total AS SILVER_TOTAL_DIAGNOSES,
       CASE WHEN g.total = s.total THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (SELECT SUM(DIAGNOSIS_COUNT) total FROM CAREVIEW_DB.GOLD.DIAGNOSIS_ANALYTICS) g,
     (SELECT COUNT(*) total FROM CAREVIEW_DB.SILVER.DIAGNOSES) s;

-- Check: Patient count should be consistent between Gold and Silver
SELECT 'UNIQUE PATIENTS' AS METRIC,
       g.cnt AS GOLD_PATIENT_COUNT,
       s.cnt AS SILVER_PATIENT_COUNT,
       CASE WHEN g.cnt = s.cnt THEN 'PASS' ELSE 'FAIL' END AS STATUS
FROM (SELECT COUNT(*) cnt FROM CAREVIEW_DB.GOLD.PATIENT_SUMMARY) g,
     (SELECT COUNT(*) cnt FROM CAREVIEW_DB.SILVER.PATIENTS) s;


-- ============================================
-- SECTION 8: FRESHNESS CHECK
-- Purpose: Check when tables were last created or modified
-- Helps identify stale data that may need refreshing
-- ============================================

SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, CREATED, LAST_ALTERED
FROM CAREVIEW_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('BRONZE', 'SILVER', 'GOLD', 'AI_READY')
ORDER BY TABLE_SCHEMA, TABLE_NAME;


-- ============================================
-- SECTION 9: AUDIT SUMMARY
-- Purpose: Quick overview of key metrics for the entire database
-- Run this for a snapshot of the current data state
-- ============================================

SELECT 
    CURRENT_TIMESTAMP() AS AUDIT_TIME,
    'CAREVIEW_DB' AS DATABASE_NAME,
    (SELECT COUNT(*) FROM CAREVIEW_DB.BRONZE.PATIENTS) AS TOTAL_PATIENTS,
    (SELECT COUNT(*) FROM CAREVIEW_DB.BRONZE.VISITS) AS TOTAL_VISITS,
    (SELECT COUNT(DISTINCT DEPARTMENT) FROM CAREVIEW_DB.SILVER.VISITS) AS TOTAL_DEPARTMENTS,
    (SELECT COUNT(DISTINCT DIAGNOSIS_CODE) FROM CAREVIEW_DB.SILVER.DIAGNOSES) AS UNIQUE_DIAGNOSES,
    (SELECT SUM(AMOUNT) FROM CAREVIEW_DB.BRONZE.BILLING) AS TOTAL_BILLED_AMOUNT;
