/*
================================================================================
HEALTHCARE DATA PLATFORM - 05 GRANTS & PERMISSIONS
================================================================================
Execution Order: 5 of 7
Dependencies: 04_databases_schemas.sql
Purpose: Grant database, schema, and object permissions to roles

RUN AS: ACCOUNTADMIN

-- ============================================================================
-- 4. GRANT PRIVILEGES TO ROLES
-- ============================================================================
-- ADMIN: Full access
GRANT ALL PRIVILEGES ON DATABASE CAREVIEW_DB TO ROLE CAREVIEW_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CAREVIEW_DB.BRONZE TO ROLE CAREVIEW_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CAREVIEW_DB.SILVER TO ROLE CAREVIEW_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CAREVIEW_DB.GOLD TO ROLE CAREVIEW_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CAREVIEW_DB.AI_READY TO ROLE CAREVIEW_ADMIN;

-- ANALYST: Read Bronze, Read/Write Silver and Gold
GRANT USAGE ON DATABASE CAREVIEW_DB TO ROLE CAREVIEW_ANALYST;
GRANT USAGE ON SCHEMA CAREVIEW_DB.BRONZE TO ROLE CAREVIEW_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CAREVIEW_DB.BRONZE TO ROLE CAREVIEW_ANALYST;
GRANT ALL PRIVILEGES ON SCHEMA CAREVIEW_DB.SILVER TO ROLE CAREVIEW_ANALYST;
GRANT ALL PRIVILEGES ON SCHEMA CAREVIEW_DB.GOLD TO ROLE CAREVIEW_ANALYST;
GRANT USAGE ON SCHEMA CAREVIEW_DB.AI_READY TO ROLE CAREVIEW_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CAREVIEW_DB.AI_READY TO ROLE CAREVIEW_ANALYST;

-- VIEWER: Read-only Gold and AI_READY
GRANT USAGE ON DATABASE CAREVIEW_DB TO ROLE CAREVIEW_VIEWER;
GRANT USAGE ON SCHEMA CAREVIEW_DB.GOLD TO ROLE CAREVIEW_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA CAREVIEW_DB.GOLD TO ROLE CAREVIEW_VIEWER;
GRANT USAGE ON SCHEMA CAREVIEW_DB.AI_READY TO ROLE CAREVIEW_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA CAREVIEW_DB.AI_READY TO ROLE CAREVIEW_VIEWER;

-- Future grants
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAREVIEW_DB.BRONZE TO ROLE CAREVIEW_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAREVIEW_DB.GOLD TO ROLE CAREVIEW_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAREVIEW_DB.AI_READY TO ROLE CAREVIEW_VIEWER;

-- ============================================================================
-- VERIFICATION
-- ============================================================================
SHOW GRANTS TO ROLE HEALTHCARE_ADMIN;
SHOW GRANTS TO ROLE HEALTHCARE_ENGINEER;
SHOW GRANTS TO ROLE HEALTHCARE_ANALYST;
SHOW GRANTS TO ROLE HEALTHCARE_SCIENTIST;
SHOW GRANTS TO ROLE HEALTHCARE_VIEWER;
